//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsEditor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RailwayCarriage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RailwayCarriage()
        {
            this.Seat = new HashSet<Seat>();
        }
    
        public int NumRailwayCarriage { get; set; }
        public int NumFlight { get; set; }
        public string Type { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual TypeRailwayCarriage TypeRailwayCarriage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seat> Seat { get; set; }
    }
}
