//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsEditor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        public int idStation { get; set; }
        public int NumFlight { get; set; }
        public int NumberInRoute { get; set; }
        public Nullable<System.TimeSpan> StopDuration { get; set; }
    
        public virtual Flight Flight { get; set; }
        public virtual Station Station { get; set; }
    }
}
