//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsEditor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Seat()
        {
            this.Ticket = new HashSet<Ticket>();
        }
    
        public int NumSeat { get; set; }
        public int NumRailwayCarriage { get; set; }
        public int NumFlight { get; set; }
        public Nullable<bool> Upper { get; set; }
        public Nullable<bool> Side { get; set; }
        public Nullable<bool> Sold { get; set; }
    
        public virtual RailwayCarriage RailwayCarriage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ticket> Ticket { get; set; }
    }
}
