//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightsEditor.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int idTicket { get; set; }
        public int Price { get; set; }
        public System.DateTime DepartureDateTime { get; set; }
        public System.DateTime ArrivalDateTime { get; set; }
        public int idDepartureStation { get; set; }
        public int idArrivalStation { get; set; }
        public int idPassenger { get; set; }
        public int NumTrain { get; set; }
        public int NumFlight { get; set; }
        public int NumRailwayCarrige { get; set; }
        public int NumSeat { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Seat Seat { get; set; }
        public virtual Station Station { get; set; }
        public virtual Station Station1 { get; set; }
        public virtual Train Train { get; set; }
    }
}
